#!/bin/sh -e

log() {
    color="$1"
    shift
    printf "\033[1;3%sm%s\033[00m\n" "$color" "$*"
}

log_noline() {
    color="$1"
    shift
    printf "\033[1;3%sm%s\033[00m" "$color" "$*"
}

panic() {
    log 1 "$1"
}

./mussel/check

log_noline 7 "cargo      :: " && cargo -V || panic "Rust: not installed, or cargo not found!"
log_noline 7 "rust musl  :: " && rustup target list --installed | grep x86_64-unknown-linux-musl || panic "Rust: target x86_64-unknown-linux-musl is not installed!"

log_noline 7 "wget       :: " && wget -V | head -n 1 || panic "Wget: not installed!"
